---
- name: loop playbook
  hosts: windows
  tasks:


    - name: Create a new group
      ansible.windows.win_group:
        name: "{{item}}"
        description: Deploy Group
        state: present
      loop: "{{ local_groups }}"
      #tags: never

    - name: Add several users
      ansible.windows.win_user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        state: absent
        groups: "{{ item.groups }}"
      loop: "{{ local_users }}"
      notify: Restart Machine
  handlers:
    - name: Restart Machine
      ansible.windows.win_reboot:
        

     