---
- name: loop playbook
  hosts: windows
  tasks:
    - name: Create a file from a Jinja2 template
      ansible.windows.win_template:
        src: /templates/file.conf.j2
        dest: C:\Temp\file.conf

    - name: Create a new group
      ansible.windows.win_group:
        name: "{{item}}"
        description: Deploy Group
        state: present
      loop: "{{ local_groups }}"
      tags: never

    - name: Add several users
      ansible.windows.win_user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        state: absent
        groups: "{{ item.groups }}"
      loop: "{{ local_users }}"
      tags: never
     # notify: Restart Machine
 # handlers:
    - name: Restart Machine
      ansible.windows.win_reboot:
      tags: never
        

     